import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  ClerkLoaded,
  ClerkLoading,
  SignIn,
  SignUp
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Header from "./components/Header";
import Image from "next/image";
import Link from "next/link";
import mainStyles from "./css/main.module.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
            <NavBar />
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              
              <UserButton />
            </SignedIn>
          </header>
          <nav> <NavBar />   </nav>
          <main className={mainStyles.main}>
            {children}


          </main>
          
        </body>
      </html>
    </ClerkProvider>
  );
}