import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  ClerkLoaded,
  ClerkLoading,
  SignIn,
  SignUp,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Clerk from "./components/Clerk";
import Image from "next/image";
import Link from "next/link";
import mainStyles from "./css/main.module.css";
import navcssStyles from "./css/navcss.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header className={navcssStyles.navcss}>
            <div className="flex gap-3 justify-between">
              <NavBar />
              <Clerk />
            </div>
          </header>
          <main className={mainStyles.main}>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
